[package]
name = "z_console_canvas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z_console_canvas_lib = { version = "0.1.0", path = "lib/z_console_canvas_lib"}
random = "*"
